swagger: '2.0'
info:
  description: This is a swagger config for Bitex Trader
  version: 0.1.1
  title: Bitex Project - Trader
host: 'localhost:8080'
schemes:
  - http
paths:
  '/user/post-test':
    post:
      tags:
        - User
      summary: user post test
      operationId: postTest
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: './dto.yaml#/definitions/PostDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: './dto.yaml#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: './dto.yaml#/definitions/UserErrorDto'