swagger: '2.0'
info:
  description: This is a swagger config for Digi Football
  version: 1.0.0
  title: Digi Football - User
host: 'localhost:8080'
schemes:
  - http
paths:
  /user/credential/sign-up:
    post:
      tags:
        - user
      summary: login with given email
      operationId: signup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/SignUpDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-contentType: application/json
      x-accepts: application/json
  /user/credential/sign-up/verify:
    get:
      tags:
        - user
      summary: login with given mobile and password
      operationId: signupVerify
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: link
          required: true
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-accepts: application/json
  /user/credential/signup/set-password:
    post:
      tags:
        - user
      summary: login with given mobile and password
      operationId: signupSetPassword
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/SignupPasswordDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-contentType: application/json
      x-accepts: application/json
  /user/credential/login/password:
    post:
      tags:
        - user
      summary: login with given mobile and password
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/LoginDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-contentType: application/json
      x-accepts: application/json
  /user/person/info:
    post:
      tags:
        - user
      summary: login with given mobile and password
      operationId: save_person_info
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/PersonInfoDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-contentType: application/json
      x-accepts: application/json
    put:
      tags:
        - user
      summary: login with given mobile and password
      operationId: update_person_info
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/PersonInfoDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-contentType: application/json
      x-accepts: application/json
    get:
      tags:
        - user
      summary: login with given mobile and password
      operationId: retrieve_person_info
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-accepts: application/json
  /user/person/picture:
    post:
      tags:
        - user
      summary: login with given mobile and password
      operationId: set_person_picture
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/PersonPictureDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-contentType: application/json
      x-accepts: application/json
    delete:
      tags:
        - user
      summary: login with given mobile and password
      operationId: unset_person_picture
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/ResponseDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ResponseDto'
      x-accepts: application/json
definitions:
  ResponseDto:
    type: object
    properties:
      code:
        type: integer
      cargo:
        type: object
  SignUpDto:
    type: object
    properties:
      email:
        type: string
  SignupPasswordDto:
    type: object
    properties:
      password:
        type: string
  LoginDto:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  PersonInfoDto:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      birthYear:
        type: integer
      birthMonth:
        type: integer
      birthDay:
        type: integer
      nationalCode:
        type: string
  PersonPictureDto:
    type: object
    properties:
      picture:
        type: string
      format:
        type: string
      width:
        type: integer
      height:
        type: integer