GET http://localhost:8080

###
POST http://localhost:8080/user/credential/sign-up
Content-Type: application/json

{
  "email": "rahmatii1366@gmail.com"
}
###
GET http://localhost:8080/user/credential/sign-up/verify?link=11a9f404-725f-4711-80ab-9b13708a652a&mail=rahmatii1366@gmail.com

###
GET http://localhost:8080/

###
POST https://gradle-digi-football.herokuapp.com/user/credential/sign-up
Content-Type: application/json

{
  "email": "rahmatii1366@gmail.com"
}
###
GET https://gradle-digi-football.herokuapp.com/user/credential/sign-up/verify?mail=rahmatii1366@gmail.com&link=de9c1196-cded-465a-b51a-e8dab5b14057

###
