GET {{user-host}}

###
GET {{user-host}}/user/sample/say-hello

###
POST {{user-host}}/user/credential/sign-up
Content-Type: application/json

{
  "email": "yaya@yahoo.com",
  "password": "123456"
}
###
POST {{user-host}}/user/credential/sign-up
Content-Type: application/json

{
  "email": "rahmatii1366@gmail.com",
  "password": "12345"
}
###
GET {{user-host}}/user/credential/sign-up/verify?link=MzgwYjg1OTItNTMzMi00NTA1LWFkZDktYWZiNDE2YTIwMWMxOnJhaG1hdGlpMTM2NkBnbWFpbC5jb20=

###